### ISSUE TITLE
创建一个基于vue_apicloud的项目是什么意思啊

### ISSUE THREAD

**Issue by lianghonglei** [xiaoqiang730730/vue_apicloud#1]
创建一个基于vue_apicloud的项目是什么意思啊，我怎么创建不了  大神解答一下吧

**Comment by xiaoqiang730730** [comment]
> 创建一个基于vue_apicloud的项目是什么意思啊，我怎么创建不了 大神解答一下吧

https://xiaoqiang730730.github.io/vue_apicloud/oneweekoneapp.html 可以先看看 这个了解下

**Comment by xiaoqiang730730** [comment]
https://xiaoqiang730730.github.io/vue_apicloud/oneweekoneapp.html 可以看看这个，了解一下

**Comment by FranklinLia** [comment]
这篇文章较老，而且apicloud_cli已经不维护了。apicloud框架里面有很多兼容性问题。
