### ISSUE TITLE
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by ftlh2005** [xiaoqiang730730/vue_apicloud#3]
npm install 提示以下错误

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 1832 packages from 1159 contributors and audited 32161 packages in 37.456s
found 13 vulnerabilities (2 low, 1 moderate, 9 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by xiaoqiang730730** [comment]
npm 包缺失 手动安装下 npm i ajv --save

**Comment by sugarnut001** [comment]
npm install ajv@^5.0.0 --save 必须要指定版本才可以，要不然还是会安装失败
