### ISSUE TITLE
api 会出现undefined

### ISSUE THREAD

**Issue by tnnevol** [xiaoqiang730730/vue_apicloud#5]
如果页面使用了api这个对象，直接用手机调试开始没问题，但是如果刷新了浏览器，再去app上调试就会出现app对象undefined； 猜测可能是浏览器环境和app切换导致出现了混乱

**Comment by tnnevol** [comment]
哈哈，自己在生命周期外面引用了，放到生命周期中就行了

**Comment by xiaoqiang730730** [comment]
https://github.com/xiaoqiang730730/vue_apicloud/blob/592146c90d7039a1930485208ce0d2abeb0a0b87/template/src/main.js#L12
所以整个在apiready之后进行vue渲染
